In [1]:
import pandas as pd
import numpy as np
from readFile import split_into_values, toRPdata
# columns 와 value는 사용자 입력
df = pd.read_csv('resources/CLAMP_resample.csv')
columns = ['chip', 'wire', 'segment']
value = ['value']
#df = pd.read_csv('resources/Dataset1.csv')
#columns = ['Process', 'Step']
#value = ['Value']

df = df.loc[:, columns + value] #('chip', 'wire', 'value')는 사용자 입력
size = 28
result = split_into_values(df, columns)
result

0         1         2         3         4         5         6     \
0     2.236858  1.909297  1.554571  1.205214  1.132879  1.176786  1.213111   
1     0.064278 -0.015003  0.130296  0.255697  0.288548  0.372255  0.487549   
2     0.069648  0.044694  0.044378  0.048168  0.054486  0.059540  0.044378   
3     0.004262  0.003630  0.007736  0.083546  0.171359  0.263910  0.351723   
4     0.121767  0.100919  0.092391  0.099340  0.123346  0.122399  0.107237   
...        ...       ...       ...       ...       ...       ...       ...   
1135  0.012159  0.011527  0.126189  0.243062  0.310344  0.389312  0.493235   
1136  0.069648  0.049116  0.033006  0.042483  0.054170  0.060487  0.052906   
1137 -0.003950 -0.009003 -0.007740 -0.004582  0.004894  0.009948  0.096497   
1138  0.068700  0.043114  0.025741  0.029532  0.054170  0.062383  0.051959   
1139  0.042483  0.006473  0.142615  0.225374  0.288864  0.425322  0.506501   

          7         8         9     ...  1243  1244  1245  1246  1247  1248  \
0     1.070968  0.866282  0.625586  ...   NaN   NaN   NaN   NaN   NaN   NaN   
1     0.563674  0.583890  0.762359  ...   NaN   NaN   NaN   NaN   NaN   NaN   
2     0.026373  0.028900  0.035217  ...   NaN   NaN   NaN   NaN   NaN   NaN   
3     0.437325  0.524506  0.615794  ...   NaN   NaN   NaN   NaN   NaN   NaN   
4     0.087968  0.080387  0.092075  ...   NaN   NaN   NaN   NaN   NaN   NaN   
...        ...       ...       ...  ...   ...   ...   ...   ...   ...   ...   
1135  0.585470  0.614530  0.763623  ...   NaN   NaN   NaN   NaN   NaN   NaN   
1136  0.035217  0.023530  0.030163  ...   NaN   NaN   NaN   NaN   NaN   NaN   
1137  0.192207  0.278756  0.370044  ...   NaN   NaN   NaN   NaN   NaN   NaN   
1138  0.037744  0.015633  0.020056  ...   NaN   NaN   NaN   NaN   NaN   NaN   
1139  0.569676  0.653699  0.750040  ...   NaN   NaN   NaN   NaN   NaN   NaN   

      1249  1250  1251  1252  
0      NaN   NaN   NaN   NaN  
1      NaN   NaN   NaN   NaN  
2      NaN   NaN   NaN   NaN  
3      NaN   NaN   NaN   NaN  
4      NaN   NaN   NaN   NaN  
...    ...   ...   ...   ...  
1135   NaN   NaN   NaN   NaN  
1136   NaN   NaN   NaN   NaN  
1137   NaN   NaN   NaN   NaN  
1138   NaN   NaN   NaN   NaN  
1139   NaN   NaN   NaN   NaN  

[1140 rows x 1253 columns]

In [2]:
from tslearn.preprocessing import TimeSeriesScalerMeanVariance, TimeSeriesResampler

# 2. 시계열 셋 크기 변경
result_ = TimeSeriesResampler(sz=size).fit_transform(result)

In [3]:
data = result_.reshape(result_.shape[0], 1, size)
data.shape

(1140, 1, 28)

In [4]:
X = toRPdata(data)
print(X.shape)

(1140, 28, 28)


In [5]:
from sklearn.preprocessing import MinMaxScaler

def MinMax(data):
    MMS = MinMaxScaler().fit(data)
    scaled = MMS.transform(data)
    return scaled

# print(X[0].shape)
# scaled_data = MinMax(X[0])
# print(scaled_data.shape)
# scaled_data = []

X_scaled = np.empty((X.shape[0], size, size))
for i, data in enumerate(X):
    X_scaled[i] = MinMax(data)
print(X_scaled.shape)
print(X_scaled)

(1140, 28, 28)
[[[0.         0.45022441 0.96667199 ... 1.         1.         1.        ]
  [0.31045155 0.         0.35611563 ... 0.68954845 0.68705713 0.66942603]
  [0.4915268  0.26259975 0.         ... 0.5084732  0.50452877 0.47661409]
  ...
  [1.         1.         1.         ... 0.         0.00802485 0.06481663]
  [0.99203903 0.98845481 0.98434339 ... 0.00796097 0.         0.05633966]
  [0.93912883 0.91172315 0.88028638 ... 0.06087117 0.05333479 0.        ]]

 [[0.         0.26391757 1.         ... 0.02404798 0.02112749 0.00870661]
  [0.20880916 0.         0.58875025 ... 0.18978262 0.19209329 0.20192057]
  [0.50774296 0.37782768 0.         ... 0.49590517 0.4973428  0.50345707]
  ...
  [0.02348326 0.23423667 0.95374972 ... 0.         0.00285191 0.0149811 ]
  [0.02069036 0.23776667 0.95925033 ... 0.00286006 0.         0.01216388]
  [0.00863146 0.25300811 0.98300033 ... 0.01520895 0.01231367 0.        ]]

 [[0.         0.83784439 0.85425719 ... 0.86956871 0.83711036 0.8681348 ]
  [0.46

In [6]:
X_scaled = np.expand_dims(X_scaled, axis=3)
X_scaled.shape

(1140, 28, 28, 1)