In [1]:
import pandas as pd
import numpy as np
from readFile import split_into_values, toRPdata
# columns 와 value는 사용자 입력
df = pd.read_csv('resources/AXISX_resample.csv')
columns = ['chip', 'wire', 'segment']
value = ['value']
#df = pd.read_csv('resources/Dataset1.csv')
#columns = ['Process', 'Step']
#value = ['Value']

df = df.loc[:, columns + value] #('chip', 'wire', 'value')는 사용자 입력
size = 28
result = split_into_values(df, columns)
result

0         1         2         3         4         5         6     \
0     1.873603  2.015115  2.033436  1.987634  1.932988  1.971524  2.002796   
1     3.417595  3.417911  3.412541  3.379690  3.314304  3.225544  3.105196   
2     3.328519  3.335468  3.329150  3.301038  3.280822  3.235020  3.174372   
3     0.184310  0.159040  0.189680  0.249064  0.339088  0.448065  0.658121   
4     0.182731  0.134718  0.157145  0.259804  0.454066  0.663175  0.883339   
...        ...       ...       ...       ...       ...       ...       ...   
1325  3.328519  3.331362  3.322201  3.297879  3.246075  3.152261  3.023068   
1326  0.203894  0.151775  0.163462  0.256329  0.390891  0.613267  0.849856   
1327  0.204842  0.149564  0.153986  0.207369  0.311923  0.477441  0.644222   
1328  0.312871  0.254118  0.295813  0.400999  0.551987  0.652119  0.694762   
1329  0.302447  0.242115  0.278756  0.391523  0.512819  0.572519  0.583890   

          7         8         9     ...  1221  1222  1223  1224  1225  1226  \
0     1.975631  1.870761  1.691660  ...   NaN   NaN   NaN   NaN   NaN   NaN   
1     2.983900  2.844916  2.692980  ...   NaN   NaN   NaN   NaN   NaN   NaN   
2     3.097615  3.018646  2.927043  ...   NaN   NaN   NaN   NaN   NaN   NaN   
3     0.966098  1.277234  1.586790  ...   NaN   NaN   NaN   NaN   NaN   NaN   
4     1.119612  1.411480  1.787370  ...   NaN   NaN   NaN   NaN   NaN   NaN   
...        ...       ...       ...  ...   ...   ...   ...   ...   ...   ...   
1325  2.872713  2.711301  2.533464  ...   NaN   NaN   NaN   NaN   NaN   NaN   
1326  1.153411  1.513191  1.939305  ...   NaN   NaN   NaN   NaN   NaN   NaN   
1327  0.861228  1.049173  1.251016  ...   NaN   NaN   NaN   NaN   NaN   NaN   
1328  0.754778  0.927561  1.158781  ...   NaN   NaN   NaN   NaN   NaN   NaN   
1329  0.622427  0.750988  0.932299  ...   NaN   NaN   NaN   NaN   NaN   NaN   

      1227  1228  1229  1230  
0      NaN   NaN   NaN   NaN  
1      NaN   NaN   NaN   NaN  
2      NaN   NaN   NaN   NaN  
3      NaN   NaN   NaN   NaN  
4      NaN   NaN   NaN   NaN  
...    ...   ...   ...   ...  
1325   NaN   NaN   NaN   NaN  
1326   NaN   NaN   NaN   NaN  
1327   NaN   NaN   NaN   NaN  
1328   NaN   NaN   NaN   NaN  
1329   NaN   NaN   NaN   NaN  

[1330 rows x 1231 columns]

In [2]:
from tslearn.preprocessing import TimeSeriesScalerMeanVariance, TimeSeriesResampler

# 2. 시계열 셋 크기 변경
result_ = TimeSeriesResampler(sz=size).fit_transform(result)

In [3]:
data = result_.reshape(result_.shape[0], 1, size)
data.shape

(1330, 1, 28)

In [4]:
X = toRPdata(data)
print(X.shape)

(1330, 28, 28)


In [5]:
from sklearn.preprocessing import MinMaxScaler

def MinMax(data):
    MMS = MinMaxScaler().fit(data)
    scaled = MMS.transform(data)
    return scaled

# print(X[0].shape)
# scaled_data = MinMax(X[0])
# print(scaled_data.shape)
# scaled_data = []

X_scaled = np.empty((X.shape[0], size, size))
for i, data in enumerate(X):
    X_scaled[i] = MinMax(data)
print(X_scaled.shape)
print(X_scaled)

(1330, 28, 28)
[[[0.         0.07514914 0.19119404 ... 0.04976746 0.41776875 0.5447409 ]
  [0.06989648 0.         0.24772673 ... 0.11618537 0.369074   0.50666542]
  [0.23639049 0.32930417 0.         ... 0.17485847 0.58245481 0.67351246]
  ...
  [0.05237398 0.13145899 0.14883365 ... 0.         0.45425611 0.57327115]
  [0.59966554 0.56958075 0.6762071  ... 0.61958917 0.         0.21807855]
  [1.         1.         1.         ... 1.         0.27890085 0.        ]]

 [[0.         0.70618007 1.         ... 1.         1.         0.03924244]
  [0.41389539 0.         0.56413348 ... 0.58281525 0.30759798 0.39089522]
  [0.94959208 0.91399501 0.         ... 0.04286122 0.58856437 0.94761395]
  ...
  [0.99211535 0.98654737 0.04478057 ... 0.         0.65970119 0.99180594]
  [0.59776745 0.31371884 0.3705008  ... 0.3974819  0.         0.58198287]
  [0.03776062 0.64175365 0.9602349  ... 0.96193928 0.93683058 0.        ]]

 [[0.         0.99169452 0.99079821 ... 0.21232637 0.99046306 0.99194303]
  [0.92

In [6]:
X_scaled = np.expand_dims(X_scaled, axis=3)
X_scaled.shape

(1330, 28, 28, 1)

In [7]:
batch_size = 32
learning_rate = 0.01
epochs = 10
optimizer='Adam'
loss='binary_crossentropy'


In [8]:
from utils import split_data, normalization_tool
from agent import Autoencoder_Agent

X_train, X_test, Y_train, Y_test = split_data(X_scaled, X_scaled) #데이터 분리

agent_28 = Autoencoder_Agent(28,optimizer,learning_rate)
agent_28.train(X_train,batch_size,epochs,X_test)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 28, 28, 16)        160       
_________________________________________________________________
activation (Activation)      (None, 28, 28, 16)        0         
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 14, 14, 16)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 14, 14, 2)         290       
_________________________________________________________________
activation_1 (Activation)    (None, 14, 14, 2)         0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 7, 7, 2)           0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 7, 7, 2)           3

In [9]:
agent_28.train(X_train,batch_size,500,X_test)

Epoch 1/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0726 - val_loss: 0.0700
Epoch 2/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0716 - val_loss: 0.0691
Epoch 3/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0710 - val_loss: 0.0698
Epoch 4/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0708 - val_loss: 0.0685
Epoch 5/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0702 - val_loss: 0.0688
Epoch 6/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0699 - val_loss: 0.0682
Epoch 7/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0699 - val_loss: 0.0680
Epoch 8/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0691 - val_loss: 0.0670
Epoch 9/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0687 - val_loss: 0.0666
Epoch 10/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0684 - val_loss: 0.0677
Epoch 11/

32/32 [==============================] - 0s 4ms/step - loss: 0.0609 - val_loss: 0.0585
Epoch 164/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0604 - val_loss: 0.0584
Epoch 165/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0602 - val_loss: 0.0591
Epoch 166/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0603 - val_loss: 0.0580
Epoch 167/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0602 - val_loss: 0.0597
Epoch 168/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0603 - val_loss: 0.0589
Epoch 169/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0608 - val_loss: 0.0594
Epoch 170/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0605 - val_loss: 0.0585
Epoch 171/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0604 - val_loss: 0.0582
Epoch 172/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0602 - val_loss: 0.0578
Epoc

32/32 [==============================] - 0s 4ms/step - loss: 0.0589 - val_loss: 0.0568
Epoch 245/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0592 - val_loss: 0.0569
Epoch 246/500
32/32 [==============================] - 0s 3ms/step - loss: 0.0589 - val_loss: 0.0566
Epoch 247/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0586 - val_loss: 0.0566
Epoch 248/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0591 - val_loss: 0.0589
Epoch 249/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0593 - val_loss: 0.0574
Epoch 250/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0593 - val_loss: 0.0578
Epoch 251/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0592 - val_loss: 0.0573
Epoch 252/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0587 - val_loss: 0.0568
Epoch 253/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0587 - val_loss: 0.0565
Epoc

32/32 [==============================] - 0s 4ms/step - loss: 0.0582 - val_loss: 0.0559
Epoch 326/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0585 - val_loss: 0.0558
Epoch 327/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0581 - val_loss: 0.0583
Epoch 328/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0590 - val_loss: 0.0558
Epoch 329/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0582 - val_loss: 0.0559
Epoch 330/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0582 - val_loss: 0.0570
Epoch 331/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0587 - val_loss: 0.0561
Epoch 332/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0580 - val_loss: 0.0560
Epoch 333/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0586 - val_loss: 0.0576
Epoch 334/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0591 - val_loss: 0.0574
Epoc

32/32 [==============================] - 0s 4ms/step - loss: 0.0582 - val_loss: 0.0559
Epoch 407/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0578 - val_loss: 0.0554
Epoch 408/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0582 - val_loss: 0.0562
Epoch 409/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0582 - val_loss: 0.0584
Epoch 410/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0584 - val_loss: 0.0561
Epoch 411/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0580 - val_loss: 0.0563
Epoch 412/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0578 - val_loss: 0.0557
Epoch 413/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0577 - val_loss: 0.0554
Epoch 414/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0582 - val_loss: 0.0597
Epoch 415/500
32/32 [==============================] - 0s 4ms/step - loss: 0.0602 - val_loss: 0.0561
Epoc

In [10]:
feature = agent_28.feature_extract(X_train)