In [21]:
def readFile(filepath):
    finalData = []
    data = pd.read_csv(filepath)
    print(data)
    uniqueChip = data['chip'].unique()
    uniqueWire = data['wire'].unique()
    uniquePar = data['parameter'].unique()
    uniqueSeg = data['segment'].unique()

    for chip in uniqueChip:
        for wire in uniqueWire:
            for par in uniquePar:
                for seg in uniqueSeg:
                    chipFilter = data.loc[data["chip"] == chip]
                    wireFilter = chipFilter.loc[data["wire"] == wire]
                    parFilter = wireFilter.loc[data["parameter"] == par]
                    segFilter = parFilter.loc[data["segment"] == seg, "value"]
                    result = segFilter.to_numpy()
                    result = np.reshape(result,(1,len(result)))
                    label = chip + "_" + wire + "_" + par +"_" +str(seg)
                    finalData[label] = result
    return finalData

In [23]:
datas = readFile("resources/AXISX_resample.csv")

          chip    wire parameter  segment     value
0        CHIP1  WIRE10     AXISX        1  1.873603
1        CHIP1  WIRE10     AXISX        1  2.015115
2        CHIP1  WIRE10     AXISX        1  2.033436
3        CHIP1  WIRE10     AXISX        1  1.987634
4        CHIP1  WIRE10     AXISX        1  1.932988
...        ...     ...       ...      ...       ...
480063  CHIP10   WIRE9     AXISX        7  0.598421
480064  CHIP10   WIRE9     AXISX        7  0.549144
480065  CHIP10   WIRE9     AXISX        7  0.520084
480066  CHIP10   WIRE9     AXISX        7  0.539036
480067  CHIP10   WIRE9     AXISX        7  0.611056

[480068 rows x 5 columns]


print(datas[1])

In [27]:
print(datas)

KeyError: 1

In [4]:
import pandas as pd
import numpy as np
from readFile import split_into_values, toRPdata
# columns 와 value는 사용자 입력
# df = pd.read_csv('resources/AXISX_resample.csv')
# # df = pd.read_csv('resources/CLAMP_resample.csv')
# columns = ['chip', 'wire', 'segment']
# value = ['value']
# #df = pd.read_csv('resources/Dataset1.csv')
# #columns = ['Process', 'Step']
# #value = ['Value']

# df = df.loc[:, columns + value] #('chip', 'wire', 'value')는 사용자 입력
# size = 96
# result = split_into_values(df, columns)

# # dataframe -> list
# result_list = result.values.tolist()


from sklearn.preprocessing import MinMaxScaler

def MinMax(data):
    MMS = MinMaxScaler().fit(data)
    scaled = MMS.transform(data)
    return scaled

# result_list transpose
result_T = [list(x) for x in zip(*result_list)]

# minmax 정규화
result_scaled = MinMax(result_T)

# 다시 result transpose 해서 원래대로
result_scaled = [list(x) for x in zip(*result_scaled)]

from tslearn.preprocessing import TimeSeriesScalerMeanVariance, TimeSeriesResampler

# 2. 시계열 셋 크기 변경
result_ = TimeSeriesResampler(sz=size).fit_transform(result_scaled)

In [15]:
print(result_.shape)
result_ = np.reshape(result_,(result_.shape[0],result_.shape[1]))
print(result_.shape)

(1330, 96, 1)
(1330, 96)


In [38]:
from sklearn.cluster import DBSCAN
from sklearn.cluster import KMeans
kmeans_result = KMeans(n_clusters=7).fit(result_)

In [43]:
import sys
import numpy

numpy.set_printoptions(threshold=sys.maxsize)
for i in range(int(np.shape(kmeans_result.labels_)[0]/ 7)):
    print(kmeans_result.labels_[i*7:(i+1)*7])

[0 0 0 1 6 2 5]
[0 0 0 1 6 2 5]
[0 0 0 1 6 2 5]
[0 0 0 1 6 2 5]
[0 0 0 1 6 2 5]
[0 0 0 1 6 2 5]
[0 0 0 1 6 2 5]
[0 0 0 1 6 2 5]
[0 0 0 1 6 2 5]
[0 0 0 1 6 2 5]
[0 4 6 1 6 2 5]
[0 0 0 1 6 2 5]
[0 0 0 1 6 2 5]
[0 0 0 1 6 2 5]
[0 0 0 1 6 2 5]
[0 0 0 1 6 2 5]
[0 0 0 1 6 2 5]
[0 0 0 1 6 2 5]
[0 0 0 1 6 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 0 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 0 0 1 6 5 5]
[0 0 0 5 6 2 5]
[0 0 0 5 6 5 5]
[0 0 0 5 6 5 5]
[0 0 0 1 6 5 5]
[0 0 0 5 6 5 5]
[0 0 0 1 6 2 5]
[0 0 0 5 6 5 5]
[0 0 0 5 6 5 5]
[0 0 0 5 6 5 5]
[0 4 0 1 6 5 5]
[0 0 0 1 6 2 5]
[0 0 0 1 6 2 5]
[0 0 0 1 6 2 5]
[0 0 0 1 6 5 5]
[0 0 0 5 6 5 5]
[0 0 0 1 6 2 5]
[0 0 0 5 6 2 5]
[0 0 0 5 6 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1 3 2 5]
[0 4 5 1

In [50]:
y_label = [0, 4, 5, 1, 3, 2, 6] * 190

In [51]:
class_ = np.array(kmeans_result.labels_)
accuracy = getAccuracy(y_label, class_)
print(accuracy)

0.6458646616541354


In [46]:
# Accuracy를 가져오는 함수
# data_y: 정답 데이터
# pred_y: 예측 데이터
def getAccuracy(data_y, pred_y):
    count = 0
    bool_array = (data_y == pred_y)
    for correct in bool_array:
        if(correct):
            count += 1
    return count / pred_y.size